/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'planning-cycles': PlanningCycle;
    programs: Program;
    bets: Bet;
    'activity-plans': ActivityPlan;
    decisions: Decision;
    'source-references': SourceReference;
    'app-state': AppState;
    media: Media;
    folders: Folder;
    tags: Tag;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'planning-cycles': PlanningCyclesSelect<false> | PlanningCyclesSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    bets: BetsSelect<false> | BetsSelect<true>;
    'activity-plans': ActivityPlansSelect<false> | ActivityPlansSelect<true>;
    decisions: DecisionsSelect<false> | DecisionsSelect<true>;
    'source-references': SourceReferencesSelect<false> | SourceReferencesSelect<true>;
    'app-state': AppStateSelect<false> | AppStateSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    folders: FoldersSelect<false> | FoldersSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'en' | 'en'[];
  globals: {
    'forecast-settings': ForecastSetting;
  };
  globalsSelect: {
    'forecast-settings': ForecastSettingsSelect<false> | ForecastSettingsSelect<true>;
  };
  locale: 'en';
  widgets: {
    collections: CollectionsWidget;
    'collection-query': CollectionQueryWidget;
    activity: ActivityWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  displayName?: string | null;
  role: 'viewer' | 'planner' | 'approver' | 'admin';
  oktaSubject?: string | null;
  figmaHandle?: string | null;
  figmaImageUrl?: string | null;
  userGroups?: string[] | null;
  makePermission?: ('view' | 'edit') | null;
  /**
   * Managed by Figma
   */
  email?: string | null;
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "planning-cycles".
 */
export interface PlanningCycle {
  id: string;
  expectedUpdatedAt?: string | null;
  name: string;
  fiscalYear: number;
  status: 'draft' | 'active' | 'locked' | 'archived';
  /**
   * Marketing-sourced pipeline target in millions.
   */
  pipelineTarget: number;
  targetMultiplier: number;
  decisionOverride?: ('fund' | 'test' | 'stop' | 're-plan' | 'pending') | null;
  /**
   * Planning methodology only. Do not paste raw customer or opportunity data.
   */
  methodologyNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: string;
  expectedUpdatedAt?: string | null;
  clientId: string;
  planningCycle: string | PlanningCycle;
  outcomeId: string;
  name: string;
  forecast: number;
  hexForecast?: number | null;
  confidence: 'high' | 'medium' | 'low';
  historyNote?: string | null;
  asanaGid?: string | null;
  asanaProjectGid?: string | null;
  owner?: string | null;
  salesforceCampaignId?: string | null;
  salesforceCampaignUrl?: string | null;
  region?: string | null;
  subRegion?: string | null;
  channel?: string | null;
  language?: string | null;
  product?: string | null;
  segment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bets".
 */
export interface Bet {
  id: string;
  expectedUpdatedAt?: string | null;
  clientId: string;
  planningCycle: string | PlanningCycle;
  outcomeId: string;
  name: string;
  region?: string | null;
  quarter?: string | null;
  owner?: string | null;
  rangeLow: number;
  rangeHigh: number;
  planningCase: number;
  hexForecast?: number | null;
  price?: number | null;
  capacity?: string | null;
  hypothesis?: string | null;
  comparable?: string | null;
  decisionRule?: string | null;
  status: 'fund' | 'test' | 'stop' | 're-plan' | 'pending';
  asanaGid?: string | null;
  asanaProjectGid?: string | null;
  dueOn?: string | null;
  salesforceCampaignId?: string | null;
  salesforceCampaignUrl?: string | null;
  subRegion?: string | null;
  channel?: string | null;
  language?: string | null;
  product?: string | null;
  segment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-plans".
 */
export interface ActivityPlan {
  id: string;
  expectedUpdatedAt?: string | null;
  externalActivityId: string;
  activityName: string;
  planningCycle: string | PlanningCycle;
  reachOverride?: number | null;
  mqlForecastOverride?: number | null;
  saoForecastOverride?: number | null;
  pipelineForecastOverride?: number | null;
  status?: ('draft' | 'submitted' | 'approved' | 'archived') | null;
  /**
   * Planning rationale only. Do not enter customer or prospect details.
   */
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decisions".
 */
export interface Decision {
  id: string;
  expectedUpdatedAt?: string | null;
  planningCycle: string | PlanningCycle;
  entityType: 'planning-cycle' | 'program' | 'bet' | 'activity-plan';
  entityId: string;
  decision: 'fund' | 'test' | 'stop' | 're-plan' | 'pending';
  rationale: string;
  reviewer: string | User;
  decisionDate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-references".
 */
export interface SourceReference {
  id: string;
  expectedUpdatedAt?: string | null;
  assetName: string;
  assetUrl: string;
  semanticAssetId?: string | null;
  sourceStatus: 'semantic-approved' | 'pending-review' | 'blocked';
  freshnessAt?: string | null;
  validatedAt?: string | null;
  releaseStatus?: string | null;
  methodologyVersion?: string | null;
  /**
   * Reference metadata only; do not paste underlying row-level data.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-state".
 */
export interface AppState {
  id: string;
  expectedUpdatedAt?: string | null;
  key: string;
  /**
   * Non-sensitive planning state only. Never store raw lead, contact, session, or opportunity data.
   */
  value:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  _h_folders?: (string | null) | Folder;
  _h_tags?: (string | Tag)[] | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders".
 */
export interface Folder {
  id: string;
  _h_folders?: (string | null) | Folder;
  name: string;
  updatedAt: string;
  createdAt: string;
  _h_slugPath?: string | null;
  _h_titlePath?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  _h_tags?: (string | null) | Tag;
  name: string;
  updatedAt: string;
  createdAt: string;
  _h_slugPath?: string | null;
  _h_titlePath?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'planning-cycles';
        value: string | PlanningCycle;
      } | null)
    | ({
        relationTo: 'programs';
        value: string | Program;
      } | null)
    | ({
        relationTo: 'bets';
        value: string | Bet;
      } | null)
    | ({
        relationTo: 'activity-plans';
        value: string | ActivityPlan;
      } | null)
    | ({
        relationTo: 'decisions';
        value: string | Decision;
      } | null)
    | ({
        relationTo: 'source-references';
        value: string | SourceReference;
      } | null)
    | ({
        relationTo: 'app-state';
        value: string | AppState;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'folders';
        value: string | Folder;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  role?: T;
  oktaSubject?: T;
  figmaHandle?: T;
  figmaImageUrl?: T;
  userGroups?: T;
  makePermission?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "planning-cycles_select".
 */
export interface PlanningCyclesSelect<T extends boolean = true> {
  expectedUpdatedAt?: T;
  name?: T;
  fiscalYear?: T;
  status?: T;
  pipelineTarget?: T;
  targetMultiplier?: T;
  decisionOverride?: T;
  methodologyNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  expectedUpdatedAt?: T;
  clientId?: T;
  planningCycle?: T;
  outcomeId?: T;
  name?: T;
  forecast?: T;
  hexForecast?: T;
  confidence?: T;
  historyNote?: T;
  asanaGid?: T;
  asanaProjectGid?: T;
  owner?: T;
  salesforceCampaignId?: T;
  salesforceCampaignUrl?: T;
  region?: T;
  subRegion?: T;
  channel?: T;
  language?: T;
  product?: T;
  segment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bets_select".
 */
export interface BetsSelect<T extends boolean = true> {
  expectedUpdatedAt?: T;
  clientId?: T;
  planningCycle?: T;
  outcomeId?: T;
  name?: T;
  region?: T;
  quarter?: T;
  owner?: T;
  rangeLow?: T;
  rangeHigh?: T;
  planningCase?: T;
  hexForecast?: T;
  price?: T;
  capacity?: T;
  hypothesis?: T;
  comparable?: T;
  decisionRule?: T;
  status?: T;
  asanaGid?: T;
  asanaProjectGid?: T;
  dueOn?: T;
  salesforceCampaignId?: T;
  salesforceCampaignUrl?: T;
  subRegion?: T;
  channel?: T;
  language?: T;
  product?: T;
  segment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-plans_select".
 */
export interface ActivityPlansSelect<T extends boolean = true> {
  expectedUpdatedAt?: T;
  externalActivityId?: T;
  activityName?: T;
  planningCycle?: T;
  reachOverride?: T;
  mqlForecastOverride?: T;
  saoForecastOverride?: T;
  pipelineForecastOverride?: T;
  status?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decisions_select".
 */
export interface DecisionsSelect<T extends boolean = true> {
  expectedUpdatedAt?: T;
  planningCycle?: T;
  entityType?: T;
  entityId?: T;
  decision?: T;
  rationale?: T;
  reviewer?: T;
  decisionDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-references_select".
 */
export interface SourceReferencesSelect<T extends boolean = true> {
  expectedUpdatedAt?: T;
  assetName?: T;
  assetUrl?: T;
  semanticAssetId?: T;
  sourceStatus?: T;
  freshnessAt?: T;
  validatedAt?: T;
  releaseStatus?: T;
  methodologyVersion?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-state_select".
 */
export interface AppStateSelect<T extends boolean = true> {
  expectedUpdatedAt?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _h_folders?: T;
  _h_tags?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders_select".
 */
export interface FoldersSelect<T extends boolean = true> {
  _h_folders?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  _h_slugPath?: T;
  _h_titlePath?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  _h_tags?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  _h_slugPath?: T;
  _h_titlePath?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forecast-settings".
 */
export interface ForecastSetting {
  id: string;
  environmentLabel: string;
  fy27Multiplier: number;
  semanticApprovedSourcesOnly: boolean;
  orgsWebFormReleaseStatus: 'blocked-ds-validation' | 'internal-validation' | 'approved';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forecast-settings_select".
 */
export interface ForecastSettingsSelect<T extends boolean = true> {
  environmentLabel?: T;
  fy27Multiplier?: T;
  semanticApprovedSourcesOnly?: T;
  orgsWebFormReleaseStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-query_widget".
 */
export interface CollectionQueryWidget {
  data?: {
    title?: string | null;
    relatedCollection:
      | 'users'
      | 'planning-cycles'
      | 'programs'
      | 'bets'
      | 'activity-plans'
      | 'decisions'
      | 'source-references'
      | 'app-state'
      | 'media'
      | 'folders'
      | 'tags';
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    sortField?: string | null;
    sortDirection?: ('asc' | 'desc') | null;
    limit?: number | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_widget".
 */
export interface ActivityWidget {
  data?: {
    excludedCollections?:
      | (
          | 'users'
          | 'planning-cycles'
          | 'programs'
          | 'bets'
          | 'activity-plans'
          | 'decisions'
          | 'source-references'
          | 'app-state'
          | 'media'
          | 'folders'
          | 'tags'
        )[]
      | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}