import { INBOUND_MODEL_FAMILIES } from "../data/model-family"

function Rule({ index, title, detail }: { index: string; title: string; detail: string }) {
  return <div className="grid grid-cols-[38px_1fr] gap-4 border-t border-brand-light-gray py-4"><span className="font-mono text-xs text-brand-medium-gray">{index}</span><div><p className="text-sm text-brand-black">{title}</p><p className="mt-1 text-xs leading-relaxed text-brand-medium-gray">{detail}</p></div></div>
}

export default function MethodologyView() {
  return <div>
    <div className="mb-8">
      <p className="mb-3 font-mono text-xs uppercase tracking-widest text-brand-medium-gray">Measure · Methodology</p>
      <h1 className="mb-3 text-4xl leading-none tracking-tight sm:text-5xl">How the forecast works</h1>
      <p className="max-w-2xl text-base leading-relaxed text-brand-medium-gray">A readable contract for model families, evidence quality, scenarios, and the rules that prevent double-counting. This page describes the implemented prototype—not a validated production model.</p>
    </div>

    <section className="mb-8 grid overflow-hidden rounded-2xl border border-brand-black bg-brand-black text-white md:grid-cols-[1.15fr_0.85fr]">
      <div className="p-8"><p className="mb-4 font-mono text-[10px] uppercase tracking-widest text-white/40">Core equation</p><p className="text-3xl leading-tight">Target = baseline engine + approved incremental bets + uncovered gap</p><p className="mt-5 max-w-2xl text-sm leading-relaxed text-white/50">Activities explain and operationalise the engine or a bet. They are not automatically added a second time at portfolio level.</p></div>
      <div className="border-t border-white/15 p-8 md:border-l md:border-t-0"><p className="mb-4 font-mono text-[10px] uppercase tracking-widest text-white/40">Identity rule</p><p className="text-xl leading-snug">Asana activity ID owns the forecast. Salesforce linkage attaches certified actuals later.</p></div>
    </section>

    <section className="mb-8">
      <div className="mb-4"><p className="mb-1 font-mono text-[10px] uppercase tracking-widest text-brand-medium-gray">Model registry</p><h2 className="text-2xl">Compatible evidence stays together</h2></div>
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {INBOUND_MODEL_FAMILIES.map(family => <article key={family.id} className={`border border-brand-light-gray bg-white p-6 ${family.forecastEligible ? "" : "border-l-2 border-l-brand-dusty-violet"}`}><div className="mb-6 flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-widest text-brand-medium-gray">{family.model}</p><h3 className="mt-2 text-xl">{family.label}</h3></div><span className={`px-2 py-1 font-mono text-[9px] uppercase ${family.forecastEligible ? "bg-brand-lime" : "border-l-2 border-brand-hot-red bg-white"}`}>{family.forecastEligible ? "Eligible source" : "Review required"}</span></div><p className="mb-6 min-h-12 text-sm leading-relaxed text-brand-medium-gray">{family.behaviouralRationale}</p><div className="border-y border-brand-light-gray py-4"><p className="font-mono text-[9px] uppercase text-brand-medium-gray">Included source</p><p className="mt-1 text-sm">{family.channels.join(", ")}</p></div><p className="mt-4 font-mono text-[10px] text-brand-medium-gray">Fallback: same family only · mature semantic evidence only · retired sources excluded</p><p className="mt-3 text-xs text-brand-medium-gray">Owner: {family.owner}</p>{family.reviewAction && <p className="mt-3 border-l-2 border-brand-hot-red bg-white p-3 text-xs leading-relaxed">Next: {family.reviewAction}</p>}</article>)}
        <article className="border border-brand-light-gray bg-white p-6"><div className="mb-6 flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-widest text-brand-medium-gray">hierarchical-campaign</p><h3 className="mt-2 text-xl">Campaign activity</h3></div><span className="border-l-2 border-brand-hot-red bg-brand-light-gray/30 px-2 py-1 font-mono text-[9px] uppercase">Not backtested</span></div><p className="mb-6 min-h-12 text-sm leading-relaxed text-brand-medium-gray">Planned webinars, events, email, ABM and other activity use compatible completed campaigns as comparables.</p><div className="border-y border-brand-light-gray py-4"><p className="font-mono text-[9px] uppercase text-brand-medium-gray">Fallback order</p><p className="mt-1 text-sm">Channel + sub-region → channel + region → channel → unavailable</p></div><p className="mt-4 font-mono text-[10px] text-brand-medium-gray">No silent geography fallback · no global cross-channel prior · minimum 8 comparables</p></article>
      </div>
    </section>

    <section className="mb-8 grid gap-4 md:grid-cols-2">
      <div className="border border-brand-light-gray bg-white p-6"><p className="mb-1 font-mono text-[10px] uppercase tracking-widest text-brand-medium-gray">Forecast lifecycle</p><h2 className="mb-5 text-xl">Preserve what was known at the time</h2><div className="flex flex-wrap gap-2">{["Draft", "Ready for review", "Approved", "Committed", "Delivered", "Matured", "Evaluated"].map((step, index) => <span key={step} className={`px-2.5 py-1.5 text-xs ${index < 4 ? "bg-brand-lime" : "bg-brand-light-gray"}`}>{step}{index < 6 ? " →" : ""}</span>)}</div><p className="mt-5 text-xs leading-relaxed text-brand-medium-gray">Approval freezes a version. Later changes create another version; actuals never overwrite the original forecast.</p></div>
      <div className="border border-brand-light-gray bg-white p-6"><p className="mb-1 font-mono text-[10px] uppercase tracking-widest text-brand-medium-gray">Scenario meaning</p><h2 className="mb-5 text-xl">Ranges before precision</h2><div className="grid grid-cols-3 gap-2"><div className="bg-brand-light-gray/45 p-3"><p className="font-mono text-[10px] uppercase">Low</p><p className="mt-2 text-xs text-brand-medium-gray">Downside planning case</p></div><div className="bg-brand-lime p-3"><p className="font-mono text-[10px] uppercase">Planning</p><p className="mt-2 text-xs text-brand-medium-gray">Operating commitment</p></div><div className="bg-brand-light-gray/45 p-3"><p className="font-mono text-[10px] uppercase">High</p><p className="mt-2 text-xs text-brand-medium-gray">Upside planning case</p></div></div><p className="mt-5 text-xs leading-relaxed text-brand-medium-gray">The prototype’s always-on scenarios are run-rate sensitivities. Campaign scenarios use empirical comparable distributions.</p></div>
    </section>

    <section className="grid gap-4 md:grid-cols-2">
      <div className="border border-brand-light-gray bg-white p-6"><p className="mb-1 font-mono text-[10px] uppercase tracking-widest text-brand-medium-gray">Non-negotiable guardrails</p><h2 className="mb-3 text-xl">What the model must never do</h2><Rule index="01" title="Never use a retired source" detail="Retired channels remain available as historical evidence but cannot enter an active prior, comparable pool, scenario, or total." /><Rule index="02" title="Never substitute missing evidence with zero" detail="Return unavailable, use a compatible proxy, or capture a documented manual case." /><Rule index="03" title="Never count the same contribution twice" detail="Every item is explicitly baseline or incremental; activities explain a contribution rather than silently duplicating it." /><Rule index="04" title="Never rewrite history" detail="Forecast versions and actuals are separate records with their own timestamps and provenance." /></div>
      <div className="border border-brand-light-gray bg-white p-6"><p className="mb-1 font-mono text-[10px] uppercase tracking-widest text-brand-medium-gray">Confidence contract</p><h2 className="mb-3 text-xl">Confidence describes evidence</h2><Rule index="H" title="High confidence" detail="Complete inputs, strong matched history, mature outcomes, stable distributions and backtested performance." /><Rule index="M" title="Medium confidence" detail="A defensible same-family proxy with visible fallback level and wider scenario range." /><Rule index="L" title="Low confidence" detail="A documented manual planning case or sparse same-family evidence that needs review." /><Rule index="—" title="Unavailable" detail="Neither compatible evidence nor an owned manual case exists. Show the exact missing input and next action." /></div>
    </section>
  </div>
}
